### ISSUE TITLE
The path visualised at the end is not the shortest path.

### ISSUE THREAD

**Issue by Rizhiy** [Tyriar/pathfinding-visualiser#76]
AFAIK, A* is supposed to find the *shortest* path to the goal, but the final path display is clearly not that.
Am I miss-understanding something or is there a bug?

Is your heuristic *admissible*?

**Comment by Tyriar** [comment]
@Rizhiy A* does not guarantee the shortest path, it finds a path if there is one but the quality of it depends on the heuristic. I think this is a dupe of https://github.com/Tyriar/pathfinding-visualiser/issues/31

Apparently I wasn't watching this repo which is the reason for the response delay 😕

**Comment by Rizhiy** [comment]
Ok, thanks
